#!/sbin/runscript

PID=/var/run/hpc_fanctl.pid
hpc_fanctl="/root/src/hpc_fanctl/hp_compaq_fanctl.sh"
nice="-1"

start() {
	ebegin "Starting HP Compaq fan control daemon"
	start-stop-daemon --start --quiet --background -m --pidfile ${PID} \
		--exec $hpc_fanctl \
	-N $nice
	eend ${?}
}

stop() {
	ebegin "Stopping HP Compaq fan control daemon"
	start-stop-daemon --stop --pidfile ${PID}
	eend ${?}
}
